port: 8080
timeout: 300
# 如需本地代理请删除下面一行proxies前的`#`号
#proxies: http://127.0.0.1:7890
#proxies-pool: https://xxx.com
ja3: 771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-16-27-5-11-43-13-51-35-23-18-17513-10-65037-45-65281,25497-29-23-24,0

mappers:
  # === newbing 代理 ===
  - addr: https://copilot.microsoft.com
    routes:
      - path: ^/copilot/turing/conversation/create
        rewrite: /turing/conversation/create
        action:
          - '{{req_setHeader "host" "sydney.bing.com"}}
             {{req_setHeader "origin" "https://copilot.microsoft.com"}}
             {{addr randomIp}}'
      - path: ^/copilot/images/kblob
        rewrite: /images/kblob
        action:
          - '{{req_setHeader "host" "sydney.bing.com"}}
             {{req_setHeader "origin" "https://copilot.microsoft.com"}}
             {{req_setHeader "referer" "https://copilot.microsoft.com"}}'
  - addr: https://www.bing.com
    routes:
      - path: ^/copilot/codex/plugins/available/get
        rewrite: /codex/plugins/available/get
  - addr: https://sydney.bing.com
    routes:
      - path: ^/copilot/sydney/ChatHub
        rewrite: /sydney/ChatHub
        action:
          - '{{req_setHeader "host" "sydney.bing.com"}}
             {{req_setHeader "origin" "https://copilot.microsoft.com"}}
             {{addr randomIp}}'
  # === gemini 代理 ===
  - addr: https://generativelanguage.googleapis.com
    routes:
      - path: ^/google/v1/(.+)
        rewrite: /v1/$1
  # === gptscopilot 代理 ===
  - addr: https://gptscopilot.ai
    routes:
      - path: ^/gpts/proxies/v1/(.+)
        rewrite: /api/$1
        action:
          - '{{$var := req_getHeader "Authorization"}}
             {{if contains $var "Bearer "}}
               {{$var = index (split $var " ") 1}}
             {{end}}
             {{$var = append "__sid__=" $var}}
             {{req_setHeader "cookie" $var}}
             {{req_setHeader "origin" "https://gptscopilot.ai"}}
             {{req_setHeader "referer" "https://gptscopilot.ai/gpts"}}
             {{req_delHeader "Authorization"}}'
  # === openai 代理 ===
  - addr: https://api.openai.com
    routes:
      - path: ^/proxies/v1/(.+)
        rewrite: /v1/$1
  # === claude 代理 ===
  - addr: https://claude.ai
    #proxies: auto
    ja3: true
    routes:
      - path: /claude/api/(.+)
        rewrite: /api/$1
  # === you 代理 ===
  - addr: https://you.com
    ja3: true
    routes:
      - path: /you/api/(.+)
        rewrite: /api/$1
  # === you rproxy 代理 ===
  - addr: https://you-rproxy-web.teralomaniac.eu.org
    routes:
      - path: /you/api/(.+)
        rewrite: /api/$1
    action:
      - '{{req_setHeader "host" "you.com"}}
         {{req_setHeader "origin" "https://you.com"}}
         {{req_setHeader "referer" "https://you.com"}}'

